-- Eliminar tablas del sistema LEX (presupuestos legales)
-- Estas tablas pertenecen a otro sistema y no deben estar en la BD de DebacuEvaluation360.
-- Se usa CASCADE para eliminar FKs dependientes en el orden correcto.
-- EJECUTAR EN SUPABASE STUDIO > SQL EDITOR

DROP TABLE IF EXISTS "LEX_INVOICE_ITEMS"   CASCADE;
DROP TABLE IF EXISTS "LEX_INVOICES"        CASCADE;
DROP TABLE IF EXISTS "LEX_BUDGET_ITEMS"    CASCADE;
DROP TABLE IF EXISTS "LEX_BUDGETS"         CASCADE;
DROP TABLE IF EXISTS "LEX_EVENTS"          CASCADE;
DROP TABLE IF EXISTS "LEX_COMMUNICATIONS"  CASCADE;
DROP TABLE IF EXISTS "LEX_DOCUMENT_VERSIONS" CASCADE;
DROP TABLE IF EXISTS "LEX_PAYMENTS"        CASCADE;
DROP TABLE IF EXISTS "LEX_LEGAL_RESOURCES" CASCADE;
DROP TABLE IF EXISTS "LEX_CASES"           CASCADE;
DROP TABLE IF EXISTS "LEX_CLIENTS"         CASCADE;
DROP TABLE IF EXISTS "LEX_SETTINGS"        CASCADE;
DROP TABLE IF EXISTS "LEX_USERS"           CASCADE;
